# Generated by Django 4.0.5 on 2022-06-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='monografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('ano', models.CharField(max_length=255)),
                ('orientador', models.CharField(max_length=255)),
                ('resumo', models.TextField()),
                ('link', models.SlugField(max_length=255, unique=True)),
            ],
        ),
    ]
