# Generated by Django 4.0.5 on 2022-06-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_monografia_link_alter_monografia_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monografia',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='monografia',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
