# Generated by Django 4.0.5 on 2022-06-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_monografia_id_alter_monografia_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monografia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
