# Generated by Django 4.0.5 on 2022-06-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_monografia_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monografia',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
