# Generated by Django 4.0.5 on 2022-06-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_monografia_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monografia',
            name='link',
            field=models.URLField(),
        ),
    ]
